### ISSUE TITLE
How to build it ?

### ISSUE THREAD

**Issue by franzejr** [argelius/react-onsenui-redux-weather#2]
Hello, I liked the app. I've downloaded and I'm able to run it locally with the commands on README. I would like to know how to build this in two ways: 1. Integrate with https://monaca.io/ 2. Build by cordova.

Thanks in advance if you can help me.

**Comment by argelius** [comment]
Hi!

Thanks for checking it out :+1: 

If you have NodeJS installed you can do:

```
npm install
npm start
```

to run it.

I will change the project to be compatible with the Monaca CLI later.

**Comment by franzejr** [comment]
Thanks, @argelius ! I have created another cordova project and I've copied the content of dist and everything was fine. I could generate a build. :)
